### PR TITLE
change Github badge name from preview to View

### PR DESCRIPTION
**Pull request by AgnieszkaZaba**
Connected to #1403.

### CODE REVIEW

**Comment by slayoo** [comment]
@AgnieszkaZaba, we would need to change all notebooks in PyMPDATA repo

**Comment by AgnieszkaZaba** [comment]
Ok, I will change in PySDM then.

**Comment by slayoo** [comment]
should be doable with a bash loop + sed one-liner

**Comment by Delcior** [comment]
this should help: find . -name "*.ipynb" -exec sed -i '' 's/View notebook/preview notebook/g' {} +

**Comment by AgnieszkaZaba** [comment]
Thank you @slayoo and @Delcior! I'm closing this PR. Github badge name stay as preview notebook.
[PySDM PR#1403](https://github.com/open-atmos/PySDM/pull/1403)

**Pull request closed without merging**
