### PR TITLE
add check if all notebooks have md with badges, md with description and Colab header

### PR DESCRIPTION
**Pull request by AgnieszkaZaba**
I added three tests proposed by @slayoo in #8. Changed order of cells in notebooks as:
1. markdown with badges
2. markdown with description
3. Colab header 

In test_third_cell_contains_colab_header I set cell index as 2.

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you @AgnieszkaZaba !
(closed and reopened the PR to trigger CI tests which were auto-disabled by GitHub due to project inactivity)

**Comment by AgnieszkaZaba** [comment]
@slayoo Should I add definitions of badge functions to test_notebooks.py or is it better to use utils?

**Comment by AgnieszkaZaba** [comment]
I added badge functions to test_notebooks.py for now. 

There is a problem with empty.ipynb because it does not have proper structure. Should we change it or maybe exclude from those tests?

**Comment by slayoo** [comment]
> I added badge functions to test_notebooks.py for now.

:+1:

> There is a problem with empty.ipynb because it does not have proper structure. Should we change it or maybe exclude from those tests?

Let's either rename it to `template.ipynb` and add there all the features that are tested, or add a separate `template.ipynb` file.

BTW, we maintain a set of "hints" for Python development here: https://github.com/open-atmos/python-dev-hints/wiki

**Review by slayoo — APPROVED** [review]

**Pull request merged**
